# Generated by Django 4.1.4 on 2022-12-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0002_tutor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutor",
            name="experience",
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="tutor", name="you", field=models.CharField(max_length=2000),
        ),
    ]
