# Generated by Django 4.1.4 on 2022-12-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0003_alter_tutor_experience_alter_tutor_you"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscribe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Email", models.CharField(max_length=200, verbose_name="Email")),
            ],
        ),
        migrations.AlterField(
            model_name="register",
            name="email",
            field=models.CharField(max_length=200, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="register",
            name="f1name",
            field=models.CharField(max_length=200, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="register",
            name="phone",
            field=models.CharField(max_length=200, verbose_name="Phone"),
        ),
        migrations.AlterField(
            model_name="register",
            name="why",
            field=models.CharField(
                max_length=2000, verbose_name="Why does the student need tutoring"
            ),
        ),
        migrations.AlterField(
            model_name="tutor",
            name="email",
            field=models.CharField(max_length=200, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="tutor",
            name="f1name",
            field=models.CharField(max_length=200, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="tutor",
            name="phone",
            field=models.CharField(max_length=200, verbose_name="Phone"),
        ),
        migrations.AlterField(
            model_name="tutor",
            name="you",
            field=models.CharField(
                max_length=2000, verbose_name="Tell us about yourself"
            ),
        ),
    ]
